const puppeteer=require('puppeteer-core');
(async()=>{const b=await puppeteer.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:'new',args:['--no-sandbox']});
const routes=['/','/about/','/contact/','/dentistry/','/aesthetics/','/fees/','/fees/membership-plan/','/referrals/','/dentistry/general-preventative/','/dentistry/general-preventative/dental-examinations/','/dentistry/general-preventative/hygiene-gum-health/','/dentistry/general-preventative/childrens-dentistry/','/dentistry/general-preventative/bruxism/','/dentistry/restorative/','/dentistry/cosmetic/','/dentistry/orthodontic/'];
const links=new Set();let bad=0;
for(const w of [1440,390]){for(const r of routes){const p=await b.newPage();await p.setViewport({width:w,height:800,isMobile:w<500,hasTouch:w<500});const e=[];p.on('response',x=>{if(x.status()>=400&&!/google|gstatic/.test(x.url()))e.push(x.status()+x.url())});p.on('pageerror',x=>e.push(x.message));
await p.goto('http://localhost:5174'+r,{waitUntil:'networkidle2'});const o=await p.evaluate(()=>[document.documentElement.scrollWidth-document.documentElement.clientWidth,[...document.images].filter(i=>i.complete&&!i.naturalWidth).length,[...document.querySelectorAll('a[href^="/"]')].map(a=>a.getAttribute('href'))]);o[2].forEach(h=>links.add(h.split('#')[0].split('?')[0]));if(o[0]>1||o[1]||e.length){bad++;console.log(w,r,o.slice(0,2),e)}await p.close()}}
for(const l of links){const res=await fetch('http://localhost:5174'+l);if(res.status!==200){bad++;console.log('broken',l,res.status)}}
const p=await b.newPage();await p.setViewport({width:390,height:800,isMobile:true,hasTouch:true});await p.goto('http://localhost:5174/',{waitUntil:'networkidle2'});await p.tap('.menu-btn');await new Promise(r=>setTimeout(r,1000));await p.screenshot({path:'v2/drawer.png'});
console.log('problems',bad);await b.close()})();
