const puppeteer=require('puppeteer-core');
(async()=>{const b=await puppeteer.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:'new',args:['--no-sandbox']});
const p=await b.newPage();await p.setViewport({width:1440,height:900});const errs=[];p.on('pageerror',e=>errs.push(e.message));p.on('dialog',d=>d.dismiss());
const T=async(n,f)=>{try{console.log(n,await f())}catch(e){console.log(n,'FAIL',e.message.slice(0,80))}};
const go=async(u)=>{await p.goto('http://localhost:5174'+u,{waitUntil:'networkidle2'});await new Promise(r=>setTimeout(r,600))};
await go('/');
await T('mega opens',async()=>{await p.hover('.has-menu > .nav-link');await new Promise(r=>setTimeout(r,600));return p.evaluate(()=>getComputedStyle(document.querySelector('.mega')).visibility)});
await T('form validate',async()=>{await p.evaluate(()=>document.querySelector('#home-form').scrollIntoView({block:'center'}));await p.click('#home-form [type=submit]');await new Promise(r=>setTimeout(r,300));return p.evaluate(()=>document.querySelectorAll('#home-form .is-bad').length)});
await T('checkbox',async()=>{await p.click('#home-form .check');return p.evaluate(()=>document.querySelector('#home-form .check input').checked)});
await T('form submit',async()=>{await p.type('#home-form-fn','A');await p.type('#home-form-ln','B');await p.type('#home-form-em','a@b.co');await p.type('#home-form-ph','01732523500');await p.type('#home-form-msg','hello');await p.evaluate(()=>{window.__nav=null;});await p.evaluate(()=>{document.querySelector('#home-form').addEventListener('submit',()=>{},{once:true})});
await Promise.race([p.click('#home-form [type=submit]'),new Promise(r=>setTimeout(r,500))]);await new Promise(r=>setTimeout(r,800));return p.evaluate(()=>document.querySelector('#home-form-done').classList.contains('is-shown'))});
await go('/about/');
await T('team dialog',async()=>{await p.evaluate(()=>document.querySelector('[data-person]').scrollIntoView({block:'center'}));await p.click('[data-person]');await new Promise(r=>setTimeout(r,700));const o=await p.evaluate(()=>[document.querySelector('#person-0').open,document.querySelector('#person-0 h3').textContent,document.querySelector('#person-0 .stack').textContent.length]);await p.screenshot({path:'v2/dialog.png'});await p.evaluate(()=>document.querySelector('#person-0 .modal-x').click());return o});
await T('mosaic caption',async()=>{await p.evaluate(()=>document.querySelectorAll('.mo')[4].click());return p.evaluate(()=>document.querySelector('[data-mcap]').textContent)});
await T('360 tab',async()=>{await p.evaluate(()=>document.querySelector('[data-mode=tour]').click());return p.evaluate(()=>[!!document.querySelector('.tour iframe').src,document.querySelector('.tour').hidden])});
await go('/fees/');
await T('acc open',async()=>{await p.evaluate(()=>document.querySelectorAll('.acc summary')[2].click());await new Promise(r=>setTimeout(r,800));return p.evaluate(()=>[...document.querySelectorAll('.acc details')].map(d=>d.classList.contains('is-open')?1:0).join(''))});
await T('fee search',async()=>{await p.type('#fee-search','hygiene');await new Promise(r=>setTimeout(r,900));return p.evaluate(()=>[...document.querySelectorAll('.acc details')].filter(d=>!d.hidden).map(d=>d.querySelector('summary').textContent.trim()))});
await go('/fees/membership-plan/');
await T('plan toggle',async()=>{await p.evaluate(()=>document.querySelector('[data-age-tabs]').scrollIntoView({block:'center'}));await p.click('[data-age-tabs] button:nth-child(2)');await new Promise(r=>setTimeout(r,300));return p.evaluate(()=>document.querySelector('[data-age-tabs]').closest('.mcard').querySelector('.price b').textContent)});
await go('/referrals/');
await T('referral flow',async()=>{await p.evaluate(()=>document.querySelector('[data-next]').click());const e1=await p.evaluate(()=>!document.querySelector('#tx-err').hidden);await p.click('.choice');await p.evaluate(()=>document.querySelector('.step.is-active [data-next]').click());await new Promise(r=>setTimeout(r,400));return [e1,await p.evaluate(()=>[...document.querySelectorAll('.step')].findIndex(s=>s.classList.contains('is-active')))]});
await go('/dentistry/general-preventative/hygiene-gum-health/');
await T('timeline',async()=>{await p.evaluate(()=>scrollTo(0,document.querySelector('.timeline').getBoundingClientRect().top+scrollY-200));await new Promise(r=>setTimeout(r,500));return p.evaluate(()=>document.querySelectorAll('.timeline li.is-on').length)});
console.log('errors',errs);await b.close()})();
